/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as HospitalRegisterRouteImport } from './routes/hospital-register'
import { Route as HospitalDashboardRouteImport } from './routes/hospital-dashboard'
import { Route as FindBloodRouteImport } from './routes/find-blood'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CampsRouteImport } from './routes/camps'
import { Route as BloodBankRegisterRouteImport } from './routes/blood-bank-register'
import { Route as BloodBankDashboardRouteImport } from './routes/blood-bank-dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRegisterRoute = HospitalRegisterRouteImport.update({
  id: '/hospital-register',
  path: '/hospital-register',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDashboardRoute = HospitalDashboardRouteImport.update({
  id: '/hospital-dashboard',
  path: '/hospital-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FindBloodRoute = FindBloodRouteImport.update({
  id: '/find-blood',
  path: '/find-blood',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsRoute = CampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => rootRouteImport,
} as any)
const BloodBankRegisterRoute = BloodBankRegisterRouteImport.update({
  id: '/blood-bank-register',
  path: '/blood-bank-register',
  getParentRoute: () => rootRouteImport,
} as any)
const BloodBankDashboardRoute = BloodBankDashboardRouteImport.update({
  id: '/blood-bank-dashboard',
  path: '/blood-bank-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blood-bank-dashboard': typeof BloodBankDashboardRoute
  '/blood-bank-register': typeof BloodBankRegisterRoute
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/find-blood': typeof FindBloodRoute
  '/hospital-dashboard': typeof HospitalDashboardRoute
  '/hospital-register': typeof HospitalRegisterRoute
  '/hospitals': typeof HospitalsRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blood-bank-dashboard': typeof BloodBankDashboardRoute
  '/blood-bank-register': typeof BloodBankRegisterRoute
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/find-blood': typeof FindBloodRoute
  '/hospital-dashboard': typeof HospitalDashboardRoute
  '/hospital-register': typeof HospitalRegisterRoute
  '/hospitals': typeof HospitalsRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blood-bank-dashboard': typeof BloodBankDashboardRoute
  '/blood-bank-register': typeof BloodBankRegisterRoute
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/find-blood': typeof FindBloodRoute
  '/hospital-dashboard': typeof HospitalDashboardRoute
  '/hospital-register': typeof HospitalRegisterRoute
  '/hospitals': typeof HospitalsRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blood-bank-dashboard'
    | '/blood-bank-register'
    | '/camps'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/find-blood'
    | '/hospital-dashboard'
    | '/hospital-register'
    | '/hospitals'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blood-bank-dashboard'
    | '/blood-bank-register'
    | '/camps'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/find-blood'
    | '/hospital-dashboard'
    | '/hospital-register'
    | '/hospitals'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/blood-bank-dashboard'
    | '/blood-bank-register'
    | '/camps'
    | '/contact'
    | '/dashboard'
    | '/donate'
    | '/find-blood'
    | '/hospital-dashboard'
    | '/hospital-register'
    | '/hospitals'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BloodBankDashboardRoute: typeof BloodBankDashboardRoute
  BloodBankRegisterRoute: typeof BloodBankRegisterRoute
  CampsRoute: typeof CampsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DonateRoute: typeof DonateRoute
  FindBloodRoute: typeof FindBloodRoute
  HospitalDashboardRoute: typeof HospitalDashboardRoute
  HospitalRegisterRoute: typeof HospitalRegisterRoute
  HospitalsRoute: typeof HospitalsRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-register': {
      id: '/hospital-register'
      path: '/hospital-register'
      fullPath: '/hospital-register'
      preLoaderRoute: typeof HospitalRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-dashboard': {
      id: '/hospital-dashboard'
      path: '/hospital-dashboard'
      fullPath: '/hospital-dashboard'
      preLoaderRoute: typeof HospitalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-blood': {
      id: '/find-blood'
      path: '/find-blood'
      fullPath: '/find-blood'
      preLoaderRoute: typeof FindBloodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps': {
      id: '/camps'
      path: '/camps'
      fullPath: '/camps'
      preLoaderRoute: typeof CampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blood-bank-register': {
      id: '/blood-bank-register'
      path: '/blood-bank-register'
      fullPath: '/blood-bank-register'
      preLoaderRoute: typeof BloodBankRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blood-bank-dashboard': {
      id: '/blood-bank-dashboard'
      path: '/blood-bank-dashboard'
      fullPath: '/blood-bank-dashboard'
      preLoaderRoute: typeof BloodBankDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BloodBankDashboardRoute: BloodBankDashboardRoute,
  BloodBankRegisterRoute: BloodBankRegisterRoute,
  CampsRoute: CampsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DonateRoute: DonateRoute,
  FindBloodRoute: FindBloodRoute,
  HospitalDashboardRoute: HospitalDashboardRoute,
  HospitalRegisterRoute: HospitalRegisterRoute,
  HospitalsRoute: HospitalsRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
